export const NOTICIAS_GENERAL = 'NOTICIAS_GENERAL';
export const NOTICIAS_SPORTS = 'NOTICIAS_SPORTS';
export const NOTICIAS_BUSINESS = 'NOTICIAS_BUSINESS';
export const NOTICIAS_HEALTH = 'NOTICIAS_HEALTH';
export const NOTICIAS_ENTERTAINMENT = 'NOTICIAS_ENTERTAINMENT';
export const NOTICIAS_TECHNOLOGY = 'NOTICIAS_TECHNOLOGY';
export const NOTICIAS_BUSQUEDA = 'NOTICIAS_BUSQUEDA';
